export enum AcordoEnum {
  NOME_POUPADOR = 'PoupadorNome',
  CPF_POUPADOR = 'PoupadorCPF',
  NR_PROCESSO = 'NumeroProcessoCNJ',
  CODIGO_BJ = 'CodigoBJ',
  UF_PROCESSO = 'UFProcesso',
  POSSUI_ADVOGADO = 'PossuiAdvogado',
  NOME_ADVOGADO = 'AdvogadoNome',
  CPF_ADVOGADO = 'AdvogadoCPF',
  OAB = 'AdvogadoOABMatricula',
  OAB_UF = 'AdvogadoOABMatriculaUF',
  CNPJ = 'AdvogadoPJCNPJ',
  RAZAO_SOCIAL = 'AdvogadoPJRazaoSocial',
  OPTANTE_SIMPLES = 'AdvogadoPJOptanteSimples',
  VL_ACORDO_PAGO = 'ValorAcordoPoupador',
  VL_HONORARIO = 'ValorHonorarios',
  VL_FEBRAPO = 'ValorFebrapo',
  VL_CUSTAS = 'ValorCustasProcessuais',
  FORMA_ACORDO = 'FormaPagamentoAcordo',
  FORMA_HONORARIO = 'FormaPagamentoHonorario',
  QTD_PARC_ACORDO = 'QtdaParcelasAcordo',
  VL_PARC_ACORDO = 'ValorParcelasAcordo',
  DEST_ACORDO = 'DestinatarioPagamentoAcordo',
  DEST_HONORARIO = 'DestinatarioPagamentoHonorario',
  NR_BANCO_POUPADOR = 'NumeroBancoPoupador',
  DS_BANCO_POUPADOR = 'NomeBancoPoupador',
  NR_AGENCIA_POUPADOR = 'NumeroAgenciaPoupador',
  NR_CONTA_POUPADOR = 'NumeroContaPoupador',
  DV_CONTA_POUPADOR = 'DvContaPoupador',
  DS_BANCO_ADVOGADO = 'NomeBancoAdvogado',
  NR_BANCO_ADVOGADO = 'NumeroBancoAdvogado',
  NR_AGENCIA_ADVOGADO = 'NumeroAgenciaAdvogado',
  NR_CONTA_ADVOGADO = 'NumeroContaAdvogado',
  DV_CONTA_ADVOGADO = 'DvContaAdvogado'
}

